import { v4 as uuidV4 } from 'uuid';

// Generated by Copilot
export class Task {
  public createdAt: Date;
  public readonly id: string;

  constructor(public title: string, public completed: boolean) {
    this.createdAt = new Date();
    this.id = uuidV4();
    this.title = title.toUpperCase();
  }
}
